const APIROUTES = {
  SENDOTP: "/auth/sendotp",
  VERIFYOTP: "/auth/verifyotp",
  ADDCATEGORY: "/category/addcategory",
  GETALLCATEGORIES: "/category/getallcategories",
  ADDSUBCATEGORY: "/category/addsubcategory",
  GETALLSUBCATEGORIES: "/category/getallsubcategories",
  ADDBUSINESS: "/business/addbusiness",
  DELETEBUSINESS: "/business/deletebusiness",
  GETALLBUSINESS: "/business/getallbusiness",
  ADDPRODUCT: "/business/addproduct",
  DELETEPRODUCT: "/business/deleteproduct",
  GETALLPRODUCTS: "/business/getproducts",
  DELETEPRODUCTIMAGES: "/business/delete-product-image",
  ADDGIFT: "/business/addgift",
  EDITGIFT: "/business/editgift",
  DELETEGIFT: "/business/deletegift",
  GETGIFTS: "/business/getgifts",
  PRODUCTRATINGS: "/product/all-ratings",
  DELETERATING: "/product/delete-rating",
  ACTIVERATINGSTATUS: "/product/rating-status",
  GETALLBUSINESSES: "/business/getallbusiness",
  ADDBASICINFO: "/business/addbasicinfo",
  GETBASICINFO: "/business/getbasicinfo",
  ADDBUSINESSINFO: "/business/addbusinessinfo",
  GETBUSINESSINFO: "/business/getbusinessinfo",
  ADDADDRESSINFO: "/business/addaddressinfo",
  GETADDRESSINFO: "/business/getaddressinfo",
  ADDBANKINFO: "/business/addbankinfo",
  UPDATEBANKINFO: "/business/updatebankinfo",
  GETBANKINFO: "/business/getbankinfo",
  ADDGIFTCARD: "/product/add-gift-card",
  DELETEGIFTCARD: "/product/delete-gift-card",
  GETGIFTCARDS: "/product/get-gift-cards",
  MERCHANTORDERS: "/order/get-merchant-orders",
  DASHBOARDCOUNT: "/home/data-count",
  PRODUCTSTOCKS: "/home/product-stocks",
  UPDATEPRODUCTSTOCK: "/home/update-product-stock",
  ORDERSTATUSUPDATE: "/order/update-status",
  ORDERITEMTATUSUPDATE: "/order/update-item-status",
  CALCULATORMERCHANTORDERS: "/monthly/merchant-orders",
  CALCULATORORDERDETAILS: "/monthly/order-detail",
  CALCULATORORDERSTATUSUPDATE: "/monthly/update-order-status",
  GETHEALTHGOALS: "/goal/gethealth-goals",

  // uploads
  UPLOADPRODUCTIMAGE: "/business/upload-product-image",
  UPLOADPRODUCTIMAGES: "/business/upload-product-images",
  UPLOADGIFTIMAGE: "/business/upload-gift-image",
};

export { APIROUTES };
